### PR TITLE
Rebuild pyglet 1.3.2 for Python 3.8

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
We need `pyglet` 1.3 for Python 3.8 over at the [`psychopy-feedstock`](https://github.com/conda-forge/psychopy-feedstock). If the tests pass, I would then create a new branch here and merge it, right?

**Comment by hoechenberger** [comment]
@cefpaf Seems I will need to patch the sources for Py 3.8 on Windows. Will look into this later today.

**Comment by hoechenberger** [comment]
@ocefpaf @bitcraft @mwcraig @jakirkham 
Ok it's building! What's the best way to proceed now? How should I name the new "old pyglet for Python 3.8" branch? :)

**Comment by hoechenberger** [comment]
Thanks @ocefpaf!

**Comment by ocefpaf** [comment]
No problem. You should be able to retry your py38 build in ~50 min (as soon as the CDNs syncs after the package is uploaded).

**Pull request merged**
