### PR TITLE
Bump to 1.3.1; update conda-forge recommendations (pip, sha256)

### PR DESCRIPTION
**Pull request by kastman**

### CODE REVIEW

**Comment by kastman** [comment]
I'll also update to 1.3.2 as soon as this is pulled in; presuming that we have to go one version at a time for the feedstock renderer?

**Comment by kastman** [comment]
Looks like Circle is failing - does the circleci need to be pulled in from some upstream to get the CI to work?

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
That should also fix the CircleCI issue.

**Comment by jakirkham** [comment]
Generally it's ok to skip to the latest version. That said, it's really up to the feedstock maintainers how they would like to do this sort of thing.

**Comment by kastman** [comment]
All combinations work except win py2, which [errors](https://ci.appveyor.com/project/conda-forge/pyglet-feedstock/build/1.0.7/job/152rf598cca7eab3#L471) with:
```
<module>
    from pyglet.libs.win32 import _kernel32, _user32, types, constants
  File "C:\bld\pyglet_1524756380932\_test_env\lib\site-packages\pyglet\libs\win32\__init__.py", line 237, in <module>
    _user32.GetRawInputData.argtypes = [HRAWINPUT, UINT, LPVOID, PUINT, UINT]
NameError: name 'PUINT' is not defined
```

Not sure why this would be undefined on only this platform. Is it possible that it was a CI error again, that just needs to be re-tested?

**Comment by jakirkham** [comment]
Just merged PR ( https://github.com/conda-forge/pyglet-feedstock/pull/3 ), which moves us to 1.3.2. So am going to close this out. That said, any help cleaning up this recipe is appreciated. Just may be easier to do in a new PR at this point. Thanks again for the help.

**Pull request closed without merging**
